# docker compose -f compose.yml -f production.yml up -d
services:
  prometheus:
    #container_name: prometheus
    #hostname: prometheus
    image: prom/prometheus:latest
    user: root
    volumes:
      - /opt/prometheus:/prometheus
      - /opt/prometheus/conf/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--storage.tsdb.retention.time=720h"
      - "--web.enable-admin-api"
      - "--web.enable-lifecycle"
    privileged: true
    networks:
      - promnet
    restart: always

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana:latest
    user: root
    volumes:
      - /opt/grafana/data:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
      #- /opt/grafana/etc:/etc/grafana
    ports:
      - "3000:3000"
    depends_on:  
      - prometheus
    privileged: true
    networks:
      - promnet
    restart: always

  alertmanager:
    # container_name: alertmanager
    # hostname: alertmanager
    image: prom/alertmanager:latest
    user: root
    volumes:
      - /opt/alertmanager/data:/var/lib/alertmanager
      - /opt/alertmanager/conf/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9093:9093"
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/var/lib/alertmanager"
    privileged: true
    networks:
      - promnet
    restart: always
  
  prometheusalert-center:
    # container_name: prometheusalert-center
    # hostname: prometheusalert-center
    image: feiyu563/prometheus-alert:latest
    user: root
    volumes:
      - /opt/prometheusalert-center/db:/app/db
      - /opt/prometheusalert-center/conf/app.conf:/app/conf/app.conf:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:8080"
    depends_on:  
      - alertmanager
    privileged: true
    networks:
      - promnet
    restart: always

  vmware_exporter:
    # container_name: vmware_exporter
    # hostname: vmware_exporter
    image: pryorda/vmware_exporter:latest
    user: root
    ports:
      - "9272:9272"
    volumes:
      - /opt/vmware/config.yml:/etc/config.yml:ro
      - /etc/localtime:/etc/localtime:ro
    #command: ["-l","DEBUG"]
    command: ["-c","/etc/config.yml"]
    privileged: true
    networks:
      - promnet
    restart: always

networks:
  promnet:
    # 定义network的名称
    name: monitor
    # 默认使用bridge单个主机上的网络，overlay代表跨多个节点的网络群
    driver: bridge
    #external: true
      